### ISSUE TITLE
File /tmp/key.json is not utf-8 encoded

### ISSUE THREAD

**Issue by f-tepel** [RafikFarhad/push-to-gcr-github-action#38]
Hi,

I can not authenticate with GCP anymore. I get the following error messages:
`
 /entrypoint.sh: line 21: [: too many arguments
Successfully decoded from base64
ERROR: (gcloud.auth.login) File /tmp/key.json is not utf-8 encoded: 'utf-8' codec can't decode byte 0xb7 in position 0: invalid start byte
Unable to login to gcloud. Exiting ..
`

The errors seem weird because I just copy the contents of my service key JSON file and pasted them as Github Secret. So its not in base64 format. I dont have to decode anything here, its plain text. What can be the issue here?

Thanks, Felix!

**Comment by RafikFarhad** [comment]
Hi @f-tepel, thanks for using this action. 
I think this is due to not escaping `"` on `$INPUT_GCLOUD_SERVICE_KEY`, for that line 21 is throwing an error. It might be decoding some prefix of the JSON texts and thus `gcloud` is unable to authenticate. 
 
I will check the action with plain JSON file; in the meantime, to quickly unblock yourself, you can use base64 secret for now.

**Comment by RafikFarhad** [comment]
For the future reader, to solve this error:
- escape `"` for your JSON key
- OR use base64 encoded string for the JSON

If possible, migrate to workload identity federation.

**Comment by RafikFarhad** [comment]
It seems like it is solved for the OP.
