### ISSUE TITLE
not working :(

### ISSUE THREAD

**Issue by johnjjung** [RafikFarhad/push-to-gcr-github-action#4]
![Screen Shot 2020-12-06 at 5 27 04 PM](https://user-images.githubusercontent.com/2654677/101294893-4b49cc00-37e8-11eb-9a9a-3e66228beaef.png)

base64'd the service account json

Would be great if you could provide better instructions on iam permissions necessary (I gave it storage admin and object viewer)

**Comment by RafikFarhad** [comment]
Hey @johnjjung, I am using the following permissions for the service account attached to this github-action. 

<img width="556" alt="Screenshot 2020-12-07 at 12 32 03 PM" src="https://user-images.githubusercontent.com/15923187/101317379-99aea780-3888-11eb-99c3-f59a57a1edaa.png">

---------------------

I think the problem is in the `object-viewer` permission. Your service account needs `object-admin` permission in order to push docker image.
Let me know if you can solve the problem.

And thanks for pointing out that our documentation needs to be more clear. We are updating it.

**Comment by RafikFarhad** [comment]
Hey @johnjjung, did the above advice solve your problem? If not then please reopen the issue.
